name: pasto_hoy
description: Events and Plans for Pasto City
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-171.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  injectable: ^2.3.0
  shared_preferences: ^2.2.1
  go_router: ^10.1.2
  intl: ^0.18.1
  rxdart: ^0.27.7
  objectbox: ^2.2.1
  objectbox_flutter_libs: any
  retrofit: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  injectable_generator: ^2.4.0
  objectbox_generator: any
  retrofit_generator: ^7.0.8
  flutter_native_splash: ^2.3.2
  icons_launcher: ^2.1.3

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/

# Instalamos Derry
# dart pub global activate derry
scripts:
  make: dart run build_runner build
  clean: dart run build_runner build --delete-conflicting-outputs
  lang: flutter gen-l10n
  icon: dart run icons_launcher:create
  splash: dart run flutter_native_splash:create

